name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastqc
  - fqtools
  - mccortex
  - mykrobe
  - picard
  - seqtk
  - trimmomatic
  - mysql
  - pip:
    - python-dateutil
    - requests
    - pysam
    - pyfastaq
    - pymysql
    - numpy
    - openpyxl
    - pyflakes
    - scipy
    - XlsxWriter




