name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - vcfdist
  - freebayes
  - snippy
  - varifier
  - fastqc
  - fqtools
  - mccortex
  - mykrobe
  - picard
  - seqtk
  - trimmomatic
  - mummer
  - libzlib
  - vcftools
  - nextflow
  - bcftools
  - minimap2
  - pip:
    - git+https://github.com/iqbal-lab-org/ivcfmerge
    - git+https://github.com/iqbal-lab-org/minos@v0.12.6



