name: base
channels:
  - conda-forge
  - bioconda
dependencies:
  - gcc
  - make
  - automake
  - vcfdist
  - freebayes
  - snippy
  - varifier
  - fastqc
  - fqtools
  - mccortex
  - mykrobe
  - picard
  - seqtk
  - trimmomatic
  - libzlib
  - pip:
    - python-dateutil
    - requests
    - pysam
    - pyfastaq
    - pymysql
    - numpy
    - openpyxl
    - pyflakes
    - scipy
    - XlsxWriter
    - tox
    - six>=1.14.0
    - git+https://github.com/iqbal-lab-org/minos@v0.12.6



